"""baseline schema

Revision ID: 1a47c85fc709
Revises: 
Create Date: 2026-09-01 23:20:26.088344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '1a47c85fc709'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The embedding columns below are of type vector, so the extension has to
    # exist before they can be created. db/init/01_init.sql also does this, but
    # that file only runs on first `docker compose up` against an empty volume —
    # a migration that silently depends on it would fail anywhere else.
    # Deliberately not dropped in downgrade(): other schemas may rely on it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('vested', sa.Boolean(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_as_of_date'), 'holdings', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_holdings_dedup_hash'), 'holdings', ['dedup_hash'], unique=True)
    op.create_index(op.f('ix_holdings_institution_id'), 'holdings', ['institution_id'], unique=False)
    op.create_index(op.f('ix_holdings_ticker'), 'holdings', ['ticker'], unique=False)
    op.create_table('ingestion_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('parser', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_ingested', sa.Integer(), nullable=False),
    sa.Column('rows_duplicate', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_log_file_hash'), 'ingestion_log', ['file_hash'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_dedup_hash'), 'transactions', ['dedup_hash'], unique=True)
    op.create_index(op.f('ix_transactions_institution_id'), 'transactions', ['institution_id'], unique=False)
    op.create_index(op.f('ix_transactions_txn_date'), 'transactions', ['txn_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_txn_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_institution_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_dedup_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_ingestion_log_file_hash'), table_name='ingestion_log')
    op.drop_table('ingestion_log')
    op.drop_index(op.f('ix_holdings_ticker'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_institution_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_dedup_hash'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_as_of_date'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_table('institutions')
    # ### end Alembic commands ###
