"""add issuer_category to transactions

Revision ID: 9aebc89a15f0
Revises: 1a47c85fc709
Create Date: 2026-09-01 23:38:25.825466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9aebc89a15f0'
down_revision: Union[str, Sequence[str], None] = '1a47c85fc709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('issuer_category', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'issuer_category')
    # ### end Alembic commands ###
